<?php

namespace Database\Seeders;

use App\Models\Charge;
use Illuminate\Database\Seeder;

class ChargeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $charges = [
            //INFRACTIONS
            ['name'=>'Driving without a Drivers License', 'chargeAmount'=>'250', 'jailTime'=>'0', 'extra'=>null, 'description'=>'The act of driving a vehicle without a license on any public road or highway.', 'category_id'=>1],
            ['name'=>'Failure to Yield for Emergency Vehicle', 'chargeAmount'=>'250', 'jailTime'=>'0', 'extra'=>null, 'description'=>'Failing to stop or yield for EMS, Fire, or Police when they are in route to a scene.', 'category_id'=>1],
            ['name'=>'Failure to Yield for Pedestrian', 'chargeAmount'=>'100', 'jailTime'=>'0', 'extra'=>null, 'description'=>'Failing to yield to pedestrians crossing a roadway within any marked or unmarked crosswalk.', 'category_id'=>1],
            ['name'=>'Illegal Parking', 'chargeAmount'=>'50', 'jailTime'=>'0', 'extra'=>null, 'description'=>null, 'category_id'=>1],
            ['name'=>'Improper Lane Usage', 'chargeAmount'=>'100', 'jailTime'=>'0', 'extra'=>null, 'description'=>null, 'category_id'=>1],
            ['name'=>'Failure to Stop For Lights/Signs', 'chargeAmount'=>'200', 'jailTime'=>'0', 'extra'=>'Continued ticketing will result in Traffic School refresh (license suspension)', 'description'=>'The act of driving a vehicle without a license on any public road or highway.', 'category_id'=>1],
            ['name'=>'Reckless Driving', 'chargeAmount'=>'1000', 'jailTime'=>'0', 'extra'=>'License suspension, 24 hour impound on vehicle', 'description'=>'When a driver breaks multiple traffic violations in one situation. For example; repeatedly swerving in and out of traffic or exceeding 50mph/80kph over the set speed limit', 'category_id'=>1],
            ['name'=>'Speeding', 'chargeAmount'=>'500', 'jailTime'=>'0', 'extra'=>null, 'description'=>'Driving a vehicle over the determined speed limit on public roads and highways', 'category_id'=>1],
            ['name'=>'Tailgating', 'chargeAmount'=>'100', 'jailTime'=>'0', 'extra'=>null, 'description'=>'To follow another vehicle more closely than is reasonable and prudent.', 'category_id'=>1],
            //MISDEMEANORS
            ['name'=>'Battery', 'chargeAmount'=>'2000', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Inflicting any willful and unlawful use of force or violence on another person.', 'category_id'=>2],
            ['name'=>'Battery - Aggravated', 'chargeAmount'=>'5000', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Touching or striking another person in a harmful or offensive manner, such that doing so causes the person to suffer a serious bodily injury', 'category_id'=>2],
            ['name'=>'Battery on a Peace / Police Officer', 'chargeAmount'=>'2000', 'jailTime'=>'5', 'extra'=>'This charge can go up to $5,000 and 36 months', 'description'=>'Willfully and unlawfully touching a peace officer or other protected official in a harmful or offensive manner, while the officer is on duty.', 'category_id'=>2],
            ['name'=>'Brandishing a Weapon or Firearm', 'chargeAmount'=>'0', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Firing a firearm in a public area or using a deadly weapon in a fight.', 'category_id'=>2],
            ['name'=>'Carrying Without a Firearm License', 'chargeAmount'=>'500', 'jailTime'=>'5', 'extra'=>null, 'description'=>'The act of carrying or displaying a legal firearm without a Firearm License in a public area, public road, or  highways.', 'category_id'=>2],
            ['name'=>'Contempt of Court', 'chargeAmount'=>'1000', 'jailTime'=>'10', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'Being disobedient to or disrespectful toward a court of law and its officers in the form of behavior that opposes or defies the authority.', 'category_id'=>2],
            ['name'=>'Defamation', 'chargeAmount'=>'1000', 'jailTime'=>'10', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'A false and unprivileged statement of fact that is harmful to someone’s reputation.', 'category_id'=>2],
            ['name'=>'Disturbing the Peace', 'chargeAmount'=>'1000', 'jailTime'=>'0', 'extra'=>null, 'description'=>'Unlawfully fight or challenge another person in a public place to fight.', 'category_id'=>2],
            ['name'=>'Driving While Under the Influence', 'chargeAmount'=>'750', 'jailTime'=>'5', 'extra'=>null, 'description'=>'Any person driving a vehicle on public roads or highways under the influence of a controlled substance past a responsible amount.', 'category_id'=>2],
            ['name'=>'Failure to Pay Government Fines', 'chargeAmount'=>'0', 'jailTime'=>'20', 'extra'=>null, 'description'=>'Failing to pay a government issued fine within 7 days issued by an officer or judge.', 'category_id'=>2],
            ['name'=>'False Information', 'chargeAmount'=>'750', 'jailTime'=>'10', 'extra'=>null, 'description'=>'Prohibits knowingly and willfully making false or fraudulent statements, or concealing information.', 'category_id'=>2],
            ['name'=>'Grand Theft', 'chargeAmount'=>'1250', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Unlawfully taking someone else\'s property when the property is valued at $950.00 or more.', 'category_id'=>2],
            ['name'=>'Indecent Exposure', 'chargeAmount'=>'500', 'jailTime'=>'5', 'extra'=>null, 'description'=>'Intentionally showing one\'s sexual organs in public.', 'category_id'=>2],
            ['name'=>'Intimidation', 'chargeAmount'=>'500', 'jailTime'=>'5', 'extra'=>null, 'description'=>'Intentionally or knowingly putting another person in fear of bodily injury.', 'category_id'=>2],
            ['name'=>'OoJ Destroying Evidence (Misdemeanor)', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'Knowingly destroying physical evidence that is in someone else\'s possession.', 'category_id'=>2],
            ['name'=>'OoJ Witness Intimidation (Misdemeanor)', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'Intimidating or tampering with witnesses knowingly and maliciously. Preventing or dissuading a witness or victim from attending a proceeding or giving testimony, or attempting to prevent or dissuade them from doing so.', 'category_id'=>2],
            ['name'=>'OoJ Obstruction of a Police Officer (Misdemeanor)', 'chargeAmount'=>'1000', 'jailTime'=>'5', 'extra'=>null, 'description'=>'Willfully resist, delay, or obstruct a police officer or emergency medical technician (EMT) in their official duties.', 'category_id'=>2],
            ['name'=>'Petty Theft', 'chargeAmount'=>'1000', 'jailTime'=>'10', 'extra'=>null, 'description'=>'Wrongfully taking or stealing someone else\'s property when the value of the property is $950 or less.', 'category_id'=>2],
            ['name'=>'Possession of a Controlled Substance', 'chargeAmount'=>'1000', 'jailTime'=>'10', 'extra'=>null, 'description'=>'Possessing a controlled substance without a valid prescription. A controlled substance can constitute both illegal and legal prescription drugs.', 'category_id'=>2],
            ['name'=>'Possession of Burglary Tools', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Possessing burglary tools with criminal intent.', 'category_id'=>2],
            ['name'=>'Prostitution', 'chargeAmount'=>'1000', 'jailTime'=>'0', 'extra'=>null, 'description'=>'The practice or occupation of engaging in sexual activity with someone for payment.', 'category_id'=>2],
            ['name'=>'Public Intoxication', 'chargeAmount'=>'300', 'jailTime'=>'1', 'extra'=>null, 'description'=>'Be under the influence of a controlled substance in a public place.', 'category_id'=>2],
            ['name'=>'Receiving Stolen Property/Goods', 'chargeAmount'=>'0', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Buys, receives, conceals, or sells any property that s/he knows to be stolen.', 'category_id'=>2],
            ['name'=>'Resisting Arrest', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>'Possible loss of gun license', 'description'=>'Willfully resisting or obstructing police officers or EMTs in the performance of their official duties.', 'category_id'=>2],
            ['name'=>'Resisting an Executive Officer', 'chargeAmount'=>'0', 'jailTime'=>'6', 'extra'=>'Possible loss of gun license', 'description'=>'Using threats or violence either to try to prevent executive officers from performing their duties, or resist executive officers in the performance of their duties.', 'category_id'=>2],
            ['name'=>'Resisting Arrest - Evading Police', 'chargeAmount'=>'500', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Willfully evading, avoiding or moving away from police officers to prevent or resist officers from performing their duties, without using threats or violence.', 'category_id'=>2],
            ['name'=>'Simple Assault', 'chargeAmount'=>'750', 'jailTime'=>'6', 'extra'=>null, 'description'=>'An unlawful attempt, coupled with a present ability, to commit a violent injury on the person of another.', 'category_id'=>2],
            ['name'=>'Stalking', 'chargeAmount'=>'500', 'jailTime'=>'5', 'extra'=>null, 'description'=>'A clear pattern of conduct in which the offender follows, harasses, or threatens another person, putting that person in fear for his or her safety.', 'category_id'=>2],
            ['name'=>'Street Racing', 'chargeAmount'=>'750', 'jailTime'=>'10', 'extra'=>null, 'description'=>'The act of two or more people knowingly entering a speed contest of any kind in any motor vehicle on public roads or highways and displays threats to public safety while doing so.', 'category_id'=>2],
            ['name'=>'Trespassing', 'chargeAmount'=>'500', 'jailTime'=>'5', 'extra'=>null, 'description'=>'When a person enters - or remains on - someone else\'s property without permission or a right to do so.', 'category_id'=>2],
            ['name'=>'Trespassing - Aggravated', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>null, 'description'=>'A person threatens to injure someone physically and then enter their home or workplace without permission.', 'category_id'=>2],
            ['name'=>'Vandalism - Aggravated', 'chargeAmount'=>'750', 'jailTime'=>'5', 'extra'=>null, 'description'=>'Deliberate destruction of or damage to public or private property.', 'category_id'=>2],
            //FELONIES
            ['name'=>'Bribery', 'chargeAmount'=>'2000', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Bribery is an effort to corruptly influence, by way of money or gift, a public official in the course of that official’s work.', 'category_id'=>3],
            ['name'=>'Burglary - First Degree', 'chargeAmount'=>'1000', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Entering any residential structure, room or locked vehicle with the intent to commit a theft or felony offense once inside.', 'category_id'=>3],
            ['name'=>'Burglary - Second Degree', 'chargeAmount'=>'2000', 'jailTime'=>'20', 'extra'=>null, 'description'=>'Entering any commercial structure, room or locked vehicle with the intent to commit a theft or felony offense once inside.', 'category_id'=>3],
            ['name'=>'Burglary of a Safe or Vault', 'chargeAmount'=>'5000', 'jailTime'=>'24', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'Entering any commercial structure, room or locked vehicle with the intent to commit a theft or felony offense once inside.', 'category_id'=>3],
            ['name'=>'Corruption of a Government Official', 'chargeAmount'=>'5000', 'jailTime'=>'0', 'extra'=>'Must either be submitted to a Judge or go through the courts. Jail time given in court.', 'description'=>'Use of powers by government officials or their network contacts for illegitimate private gain.', 'category_id'=>3],
            ['name'=>'Drive by Shooting', 'chargeAmount'=>'2000', 'jailTime'=>'24', 'extra'=>null, 'description'=>'A person to willfully and maliciously to fire a gun from a vehicle.', 'category_id'=>3],
            ['name'=>'Extortion', 'chargeAmount'=>'5000', 'jailTime'=>'30', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'Using force or threats to compel another person to give you money or property, or to compel a public officer to perform an official act.', 'category_id'=>3],
            ['name'=>'Grand Theft Auto', 'chargeAmount'=>'1000', 'jailTime'=>'10', 'extra'=>null, 'description'=>'To take someone else\'s vehicle, worth $950 or more, without permission, with the intent to deprive the true owner of the vehicle.', 'category_id'=>3],
            ['name'=>'Grand Theft Firearm', 'chargeAmount'=>'5000', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Is only considered GFF if one of the following is true:<br>The firearm(s) that were stolen are worth more than $950, or the defendant has a prior conviction for one of a short list of particularly serious felonies (such as murder).', 'category_id'=>3],
            ['name'=>'Hit and Run', 'chargeAmount'=>'500', 'jailTime'=>'6', 'extra'=>null, 'description'=>'Leaving the scene of a vehicular accident without identifying to others involved.', 'category_id'=>3],
            ['name'=>'Impersonation of a Government Official', 'chargeAmount'=>'2000', 'jailTime'=>'12', 'extra'=>null, 'description'=>'Fraudulently to pretend to be, or to impersonate, a police officer. This may include wearing a police uniform or displaying a fake badge.', 'category_id'=>3],
            ['name'=>'Inciting Riots', 'chargeAmount'=>'1000', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts', 'description'=>'A person intending to cause a riot, s/he urges other people to: engage in rioting, commit acts of force or violence, or burn or destroy property.', 'category_id'=>3],
            ['name'=>'Kidnapping', 'chargeAmount'=>'750', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts. If this was a kidnapping associated with a robbery/hostage situation then police can submit the charge without contacting a lawyer/DOJ.', 'description'=>'Moving another person a substantial distance, without the person\'s consent, by means of using force or fear.', 'category_id'=>3],
            ['name'=>'Kidnapping- Aggravated', 'chargeAmount'=>'1250', 'jailTime'=>'36', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'If you move another person and: use force, fear or fraud upon a victim who is a child under 14 years of age, accompany the kidnapping with a demand for ransom, or cause the victim to suffer serious bodily harm or death.', 'category_id'=>3],
            ['name'=>'Manslaughter - Voluntary', 'chargeAmount'=>'2000', 'jailTime'=>'100', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'A person commits this crime by killing another human being during a sudden quarrel, in the heat of passion, or based on an honest but unreasonable belief in the need to defend oneself.', 'category_id'=>3],
            ['name'=>'Manslaughter - Voluntary Attempted', 'chargeAmount'=>'3500', 'jailTime'=>'40', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Attempting to and knowingly trying to kill another human being during a sudden quarrel, in the heat of passion, or based on an honest but unreasonable belief in the need to defend oneself.', 'category_id'=>3],
            ['name'=>'Manslaughter - Involuntary', 'chargeAmount'=>'5000', 'jailTime'=>'30', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Unintentional killing of another person, while committing either a crime that is not an inherently dangerous felony or a lawful act which might produce death.', 'category_id'=>3],
            ['name'=>'Manufacturing of Controlled Substances', 'chargeAmount'=>'5000', 'jailTime'=>'36', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'To manufacture a controlled substance. This section applies to narcotics such as ecstasy, heroin, cocaine, and opiates.', 'category_id'=>3],
            ['name'=>'Manufacturing Firearms', 'chargeAmount'=>'5000', 'jailTime'=>'120', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Manufacturing, selling, and/or possessing certain dangerous weapons.', 'category_id'=>3],
            ['name'=>'Murder - Capital', 'chargeAmount'=>'0', 'jailTime'=>'0', 'extra'=>'Must either be submitted to a Judge or go through the courts. Hold Till Trial.', 'description'=>'Capital murder is first-degree murder with special circumstances. And can only be charged to a person by a court conviction.', 'category_id'=>3],
            ['name'=>'Murder - First Degree', 'chargeAmount'=>'5000', 'jailTime'=>'300', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Willful, deliberate and premeditated action of killing another person with malice aforethought.', 'category_id'=>3],
            ['name'=>'Murder - First Degree Attempted', 'chargeAmount'=>'5000', 'jailTime'=>'200', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'The willful, deliberate, and premeditated attempt to kill another person with malice and aforethought.', 'category_id'=>3],
            ['name'=>'Murder - Second Degree', 'chargeAmount'=>'4000', 'jailTime'=>'150', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Second-degree murder is taking of another person\'s life. But it is not deliberate and premeditated.', 'category_id'=>3],
            ['name'=>'Murder - Second Degree Attempted', 'chargeAmount'=>'3000', 'jailTime'=>'200', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'An attempted murder that is willful, but not deliberate and premeditated.', 'category_id'=>3],
            ['name'=>'Murder - Felony 1st Degree', 'chargeAmount'=>'2500', 'jailTime'=>'300', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Killing while committing a dangerous felony. Applies during the commission of: arson, robbery, burglary, carjacking, kidnapping, riots, torture.', 'category_id'=>3],
            ['name'=>'Murder - Felony 2nd Degree', 'chargeAmount'=>'2500', 'jailTime'=>'180', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'felony-murder rule attaches to felonies that are: Inherently dangerous, and not included under the first-degree felony-murder rule.', 'category_id'=>3],
            ['name'=>'OoJ Witness Intimidation (Felony)', 'chargeAmount'=>'5000', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Intimidating or tampering with witnesses knowingly and maliciously that is accompanied by force or a threat of force against a witness, victim, third party, or anyone\'s property; it furthers a conspiracy; the person doing it is being paid; or the person doing it has a prior conviction for intimidating or tampering with a witness.', 'category_id'=>3],
            ['name'=>'OoJ Offering False Evidence (Felony)', 'chargeAmount'=>'5000', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'To offer physical evidence that is known to be forged or fraudulent. It applies to any official hearing or investigation, including: Trials, Official proceedings, Inquiries and Investigations. The evidence can be completely or partially altered or fabricated. As long as it is false, but presented as true.', 'category_id'=>3],
            ['name'=>'OoJ Prepare False Evidence (Felony)', 'chargeAmount'=>'5000', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'To allow it or intend for it to be used in an official hearing or investigation. The evidence has to be physical, like a: book, paper, record, instrument in writing or digital document/file.', 'category_id'=>3],
            ['name'=>'OoJ Tampering of Evidence', 'chargeAmount'=>'2500', 'jailTime'=>'12', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'To plant or tamper with evidence for the purpose of causing someone to be charged with a crime, or to be produced with a deceptive effect at a legal proceeding.', 'category_id'=>3],
            ['name'=>'Pimping', 'chargeAmount'=>'1000', 'jailTime'=>'6', 'extra'=>null, 'description'=>'A person commits “pimping” if s/he receives all or part of the revenue from another person’s work as a prostitute.', 'category_id'=>3],
            ['name'=>'Possession of a Class 1 Firearm', 'chargeAmount'=>'1000', 'jailTime'=>'12', 'extra'=>'Gun confiscation.', 'description'=>'Possession of handguns, rifles and shotguns which are illegal or without proper License.', 'category_id'=>3],
            ['name'=>'Possession of a Class 2 Firearm', 'chargeAmount'=>'2000', 'jailTime'=>'24', 'extra'=>'Gun confiscation, Gun License removed.', 'description'=>'Possession of handguns, rifles, shotguns and silencers which are semi-automatic, which are illegal or without proper License.', 'category_id'=>3],
            ['name'=>'Possession of a Class 3 Firearm', 'chargeAmount'=>'5000', 'jailTime'=>'36', 'extra'=>'Gun confiscation, Gun License removed.', 'description'=>'Possession of SBRs, SBS, Fully Automatic Rifles and Handguns which are illegal or without proper License.', 'category_id'=>3],
            ['name'=>'Possession with Intent to Sell', 'chargeAmount'=>'5000', 'jailTime'=>'24', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Unlawful possession of a controlled substance, knowledge the illegal substance was present and was illegal in nature, and intent to sell the controlled substance while in possession of the controlled substance.', 'category_id'=>3],
            ['name'=>'Prison Break', 'chargeAmount'=>'5000', 'jailTime'=>'300', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'For a prisoner to attempt to escape custody. A prisoner may include: an inmate in prison, a person in an officer’s lawful custody.', 'category_id'=>3],
            ['name'=>'Prison Break from Outside Help', 'chargeAmount'=>'5000', 'jailTime'=>'300', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'For a person to rescue, help in rescuing, or attempt to rescue a prisoner of the state. A prisoner may include: an inmate in prison, a person in an officer’s lawful custody.', 'category_id'=>3],
            ['name'=>'Robbery', 'chargeAmount'=>'750', 'jailTime'=>'30', 'extra'=>null, 'description'=>'Taking of personal property in the possession of another, from his/her person or immediate presence, and against his/her will, accomplished by means of force or fear.', 'category_id'=>3],
            ['name'=>'Robbery - Armed', 'chargeAmount'=>'1250', 'jailTime'=>'30', 'extra'=>null, 'description'=>'The use of a lethal weapon to perpetrate violence or the threat of violence (intimidation) against a victim while performing theft.', 'category_id'=>3],
            ['name'=>'Vehicular Manslaughter', 'chargeAmount'=>'1500', 'jailTime'=>'20', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'Causing the death of another person while driving a vehicle, by negligently committing either an unlawful act that is not a felony, or a lawful act that may cause death.', 'category_id'=>3],
            ['name'=>'Vehicular Manslaughter While Intoxicated', 'chargeAmount'=>'2000', 'jailTime'=>'24', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'A defendant both drives under the influence and engages in some additional negligent behavior while driving, and as a result, another person is killed.', 'category_id'=>3],
            ['name'=>'Vehicular Manslaughter - Gross', 'chargeAmount'=>'2500', 'jailTime'=>'36', 'extra'=>'Must either be submitted to a Judge or go through the courts.', 'description'=>'When a motorist, while under the influence of alcohol or drugs and driving with gross negligence, causes an accident in which another person is killed.', 'category_id'=>3],
            ['name'=>'Vigilantism', 'chargeAmount'=>'500', 'jailTime'=>'12', 'extra'=>null, 'description'=>'The actions of a single person or group of people who claim to enforce the law but lack the legal authority to do so.', 'category_id'=>3]
        ];

        Charge::insert($charges);
    }
}
